version: '3.1'

services:
  mysql:
    image: mysql:8.0.27
    restart: always
    command: --default-authentication-plugin=mysql_native_password --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./lib/INIT_DB.sql:/docker-entrypoint-initdb.d/init.sql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

  phpmyadmin:
    image: phpmyadmin:5.1.1
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
    depends_on:
      - mysql

  nextjs:
    ports:
      - 3000:3000
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - phpmyadmin
      
volumes:
  mysql_data: