import { Button } from '@chakra-ui/button'
import { Container, Flex } from '@chakra-ui/layout'
import type { NextPage, GetServerSideProps } from 'next'
import Head from 'next/head'
import React, { useState } from 'react'
import CardList from '../components/CardList'
import { getAllAvailableCategories } from '../helpers'
import Product from '../intefaces/product'
import { mockedProductsType } from './api/get-products'

interface HomeProps {
  products: Array<Product>
}

const Home: NextPage<HomeProps> = ({ products }) => {
  const [displayedProducts, setDisplayedProducts] =
    useState<Array<Product>>(products)
  const categories = getAllAvailableCategories(products)

  const handleClick = (
    event: React.MouseEvent<HTMLButtonElement, MouseEvent>
  ) => {
    const category = event.currentTarget.name

    if (category === 'all') {
      setDisplayedProducts(products)
    } else {
      setDisplayedProducts(
        products.filter((product) => product.categories.includes(category))
      )
    }
  }
  return (
    <>
      <Head>
        <title>Alternative Freshly Cosmetics - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW="container.xl">
        <Flex justifyContent="center" alignItems="center" gridGap={2} my={4}>
          <Button name="all" onClick={handleClick}>
            All
          </Button>
          {categories.map((category) => (
            <Button key={category} name={category} onClick={handleClick}>
              {category}
            </Button>
          ))}
        </Flex>
        <CardList products={displayedProducts} />
      </Container>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const response = await fetch('http://localhost:3000/api/get-products')
  const products: mockedProductsType = await response.json()

  return {
    props: { products },
  }
}
export default Home
